# -*- coding: utf-8 -*-
"""Inventario de telas, ligacoes de prototipo e decisoes pendentes.

Fonte unica usada pelo mapa de navegacao (tela 56), pela tela de decisoes (57)
e pelos documentos markdown gerados.
"""

MODULOS = [
    ("publico", "MÓDULO PÚBLICO", "Acesso livre, sem login"),
    ("auth", "AUTENTICAÇÃO", "RF 5 e RF 6"),
    ("aluno", "ÁREA DO ALUNO", "RF 7, RF 8 e RF 9"),
    ("gestor", "ÁREA DO GESTOR", "RF 10 a RF 17"),
    ("prof", "ÁREA DO PROFESSOR", "Acesso restrito"),
    ("apoio", "APOIO À REUNIÃO", "Não faz parte do sistema"),
]

# (numero, arquivo, titulo curto, modulo, requisitos)
TELAS = [
    ("01", "01-home", "Home do portal", "publico", "RF 1, RF 3, RF 4"),
    ("02", "02-cursos-vitrine", "Vitrine de cursos e eventos", "publico", "RF 1"),
    ("03", "03-cursos-filtros-aplicados", "Vitrine com filtros aplicados", "publico", "RF 1"),
    ("04", "04-cursos-realizados", "Cursos e eventos realizados", "publico", "RF 1"),
    ("05", "05-curso-detalhe-ementa", "Detalhe do curso - Ementa", "publico", "RF 2"),
    ("06", "06-curso-detalhe-professor", "Detalhe do curso - Professor", "publico", "RF 2, RF 16"),
    ("07", "07-curso-detalhe-cronograma-turmas", "Detalhe - Cronograma e turmas", "publico", "RF 2, RF 13"),
    ("08", "08-noticias-lista", "Notícias", "publico", "RF 3"),
    ("09", "09-noticia-detalhe", "Notícia aberta", "publico", "RF 3"),
    ("10", "10-escola-quem-somos", "A Escola - Quem Somos", "publico", "Estrutura"),
    ("11", "11-escola-historia", "A Escola - História", "publico", "Estrutura"),
    ("12", "12-escola-legislacao-transparencia", "Legislação e Transparência", "publico", "Estrutura"),
    ("13", "13-escolas-parceiras", "Escolas parceiras", "publico", "Estrutura"),
    ("14", "14-acervo-biblioteca", "Acervo / Biblioteca", "publico", "Estrutura"),
    ("15", "15-contato", "Contato", "publico", "Estrutura"),
    ("16", "16-busca-resultados", "Resultados da busca", "publico", "Busca rápida"),
    ("17", "17-validar-certificado", "Validar certificado", "publico", "RF 4"),
    ("18", "18-certificado-valido", "Certificado válido (Cenário B)", "publico", "RF 4"),
    ("19", "19-certificado-invalido", "Certificado inválido (Cenário A)", "publico", "RF 4"),
    ("20", "20-certificado-pdf-opcao1-codigo", "PDF do certificado - Opção 1", "publico", "RF 4"),
    ("21", "21-certificado-pdf-opcao2-qrcode", "PDF do certificado - Opção 2", "publico", "RF 4"),
    ("22", "22-login", "Login", "auth", "RF 5"),
    ("23", "23-login-erro-e-bloqueio", "Login com erro e bloqueio", "auth", "RF 5"),
    ("24", "24-cadastro-aluno", "Cadastro do aluno", "auth", "RF 6"),
    ("25", "25-cadastro-confirmacao", "Cadastro concluído", "auth", "RF 5, RF 6"),
    ("26", "26-senha-esqueci", "Esqueci minha senha", "auth", "RF 5"),
    ("27", "27-senha-link-enviado", "Link de recuperação enviado", "auth", "RF 5"),
    ("28", "28-senha-nova", "Criar nova senha", "auth", "RF 5"),
    ("29", "29-aluno-painel", "Painel do aluno", "aluno", "Estrutura"),
    ("30", "30-aluno-inscricao-selecionar-turma", "Inscrição - escolher turma", "aluno", "RF 7"),
    ("31", "31-aluno-inscricao-sem-vaga-outra-turma", "Inscrição - turma esgotada", "aluno", "RF 7, RF 8"),
    ("32", "32-aluno-inscricao-confirmada", "Inscrição confirmada", "aluno", "RF 7"),
    ("33", "33-aluno-lista-espera-confirmada", "Entrou na lista de espera", "aluno", "RF 8"),
    ("34", "34-aluno-meus-cursos", "Meus cursos", "aluno", "RF 7, RF 8, RF 9"),
    ("35", "35-aluno-cancelar-inscricao", "Cancelar inscrição (aluno)", "aluno", "RF 9"),
    ("36", "36-aluno-sala-do-curso-materiais", "Sala do curso e materiais", "aluno", "RF 2, RF 14"),
    ("37", "37-aluno-meus-certificados", "Meus certificados", "aluno", "RF 4, RF 15"),
    ("38", "38-aluno-atualizar-dados", "Atualizar meus dados", "aluno", "RF 6"),
    ("39", "39-gestor-painel", "Painel do gestor", "gestor", "RF 10-17"),
    ("40", "40-gestor-cursos-lista", "Gestão de cursos", "gestor", "RF 12"),
    ("41", "41-gestor-curso-cadastro", "Cadastro de curso", "gestor", "RF 12"),
    ("42", "42-gestor-turmas", "Gestão de turmas", "gestor", "RF 13"),
    ("43", "43-gestor-inscricoes", "Gestão de inscrições", "gestor", "RF 11, RF 13"),
    ("44", "44-gestor-cancelar-inscricao-log", "Cancelar inscrição + log", "gestor", "RF 11"),
    ("45", "45-gestor-fila-espera", "Gestão da fila de espera", "gestor", "RF 8, RF 10"),
    ("46", "46-gestor-frequencia", "Controle de frequência", "gestor", "RF 14"),
    ("47", "47-gestor-certificados-emissao", "Emissão de certificados", "gestor", "RF 4, RF 15"),
    ("48", "48-gestor-professores", "Gestão de professores", "gestor", "RF 16"),
    ("49", "49-gestor-conteudo-noticias", "Conteúdo - Notícias", "gestor", "RF 3, RF 17"),
    ("50", "50-gestor-conteudo-acervo", "Conteúdo - Acervo", "gestor", "RF 17"),
    ("51", "51-gestor-conteudo-parceiras-e-paginas", "Conteúdo - Parceiras e páginas", "gestor", "RF 17"),
    ("52", "52-gestor-relatorios", "Relatórios e indicadores", "gestor", "RF 12-15"),
    ("53", "53-professor-painel", "Painel do professor", "prof", "Estrutura"),
    ("54", "54-professor-alunos-inscritos", "Alunos inscritos", "prof", "Estrutura"),
    ("55", "55-professor-materiais-upload", "Materiais do curso", "prof", "Estrutura"),
    ("56", "56-mapa-de-navegacao", "Mapa de navegação", "apoio", "-"),
    ("57", "57-decisoes-em-reuniao", "Decisões em reunião", "apoio", "-"),
]

TELA_POR_NUM = {t[0]: t for t in TELAS}

# (origem, elemento clicavel, destino, observacao)
LINKS = [
    # ---------------- fluxo publico
    ("01", "Menu 'Cursos e Eventos' / botão 'Ver agenda completa'", "02", "Entrada da agenda"),
    ("01", "Botão 'Ver detalhes' de um card de curso", "05", "Abre a página do curso"),
    ("01", "Aba 'Cursos e eventos realizados'", "04", "Aba de concluídos do RF 1"),
    ("01", "Acesso rápido 'Validar certificado'", "17", "Ícone de acesso rápido"),
    ("01", "Acesso rápido 'Área do Aluno'", "22", "Exige login"),
    ("01", "Acesso rápido 'Agenda de cursos'", "02", ""),
    ("01", "Acesso rápido 'Acervo / Biblioteca'", "14", ""),
    ("01", "Botão 'Buscar' da barra de busca rápida", "16", "Busca por texto simples"),
    ("01", "Link 'Ver todas as notícias'", "08", ""),
    ("01", "Card de notícia 'Ler notícia completa'", "09", ""),
    ("01", "Link 'Ver todas as parcerias' / card de escola parceira", "13", ""),
    ("01", "Link 'Ver todos os instrumentos'", "12", ""),
    ("01", "Link 'Ir para o acervo'", "14", ""),
    ("01", "Menu 'A Escola'", "10", ""),
    ("01", "Menu 'Notícias'", "08", ""),
    ("01", "Menu 'Contato'", "15", ""),
    ("01", "Botão 'Entrar / Cadastre-se' do cabeçalho", "22", "Vale para todas as páginas públicas"),
    ("02", "Botão 'Aplicar' da barra de filtros", "03", "Mostra o resultado filtrado"),
    ("02", "Aba 'Cursos e eventos realizados'", "04", ""),
    ("02", "Botão 'Ver detalhes' de um card", "05", ""),
    ("02", "Logo / menu 'Home'", "01", ""),
    ("03", "Link 'Limpar filtros'", "02", ""),
    ("03", "Botão 'Ver detalhes' de um card", "05", ""),
    ("04", "Aba 'Com inscrições abertas'", "02", ""),
    ("04", "Botão 'Ver informações' de um card", "05", ""),
    ("05", "Aba 'Sobre o professor'", "06", ""),
    ("05", "Aba 'Cronograma e turmas'", "07", ""),
    ("05", "Botão 'Inscrever-se neste curso' (usuário deslogado)", "22", "RF 7: redireciona ao login"),
    ("05", "Botão 'Inscrever-se neste curso' (usuário logado)", "30", "RF 7: vai escolher a turma"),
    ("05", "Link 'Ir para a validação de certificados'", "17", ""),
    ("06", "Aba 'O que você vai aprender'", "05", ""),
    ("06", "Aba 'Cronograma e turmas'", "07", ""),
    ("07", "Aba 'O que você vai aprender'", "05", ""),
    ("07", "Aba 'Sobre o professor'", "06", ""),
    ("07", "Botão 'Inscrever-se neste curso'", "30", ""),
    ("08", "Card de notícia / botão 'Ler notícia'", "09", ""),
    ("09", "Botão 'Voltar'", "08", ""),
    ("10", "Aba 'História'", "11", ""),
    ("10", "Aba 'Legislação e Transparência'", "12", ""),
    ("10", "Aba 'Escolas parceiras'", "13", ""),
    ("11", "Aba 'Quem Somos'", "10", ""),
    ("12", "Aba 'Escolas parceiras'", "13", ""),
    ("13", "Aba 'Quem Somos'", "10", ""),
    ("16", "Resultado do tipo curso", "05", ""),
    ("16", "Resultado do tipo notícia", "09", ""),
    ("16", "Resultado do tipo acervo", "14", ""),
    ("17", "Botão 'Validar certificado' com código correto", "18", "Cenário B do RF 4"),
    ("17", "Botão 'Validar certificado' com código errado", "19", "Cenário A do RF 4"),
    ("18", "Botão 'Validar outro código'", "17", ""),
    ("19", "Botão 'Validar novamente'", "18", ""),
    # ---------------- autenticacao
    ("22", "Botão 'Entrar' (sucesso)", "29", "RF 5 Cenário A"),
    ("22", "Botão 'Entrar' (credencial errada)", "23", "RF 5 Cenário B"),
    ("22", "Atalho do protótipo 'Entrar como Aluno'", "29", ""),
    ("22", "Atalho do protótipo 'Entrar como Gestor'", "39", ""),
    ("22", "Atalho do protótipo 'Entrar como Professor'", "53", ""),
    ("22", "Link 'Esqueci minha senha'", "26", ""),
    ("22", "Link 'Cadastre-se'", "24", ""),
    ("22", "Link 'Voltar ao portal'", "01", ""),
    ("23", "Botão 'Entrar' (agora correto)", "29", ""),
    ("23", "Link 'Esqueci minha senha'", "26", ""),
    ("24", "Botão 'Criar meu cadastro'", "25", ""),
    ("24", "Botão 'Ir para o login'", "22", ""),
    ("25", "Botão 'Continuar a inscrição no curso'", "30", "RF 5 Cenário A: volta para a inscrição"),
    ("25", "Botão 'Ir para Área do Aluno'", "29", ""),
    ("25", "Botão 'Início'", "01", ""),
    ("26", "Botão 'Enviar link de recuperação'", "27", ""),
    ("27", "Botão 'Voltar para o login'", "22", ""),
    ("27", "Link do e-mail (simular clique)", "28", "Token válido por 2 horas"),
    ("28", "Botão 'Salvar nova senha'", "22", ""),
    # ---------------- area do aluno
    ("29", "Aba 'Meus cursos'", "34", ""),
    ("29", "Aba 'Meus certificados'", "37", ""),
    ("29", "Aba 'Meus dados' / botão 'Atualizar meus dados'", "38", ""),
    ("29", "Link 'Acessar' de uma próxima atividade", "36", ""),
    ("29", "Botão 'Ir para validação'", "17", ""),
    ("29", "Botão 'Sair da conta'", "01", ""),
    ("30", "Botão 'Confirmar inscrição' (com vaga)", "32", "RF 7: grava status Confirmada"),
    ("30", "Seleção da turma esgotada", "31", "RF 7: sem vaga na turma"),
    ("30", "Botão 'Cancelar e voltar ao curso'", "05", ""),
    ("31", "Botão 'Escolher' de uma turma com vaga", "30", ""),
    ("31", "Botão 'Entrar na lista de espera'", "33", "RF 8"),
    ("32", "Botão 'Ir para Meus Cursos'", "34", ""),
    ("32", "Botão 'Ver outros cursos'", "02", ""),
    ("33", "Botão 'Ir para Meus Cursos'", "34", ""),
    ("33", "Botão 'Ver outras turmas'", "07", ""),
    ("34", "Botão 'Cancelar' de uma inscrição", "35", "RF 9: abre a confirmação"),
    ("34", "Botão 'Acessar curso'", "36", ""),
    ("34", "Botão 'Certificado'", "37", ""),
    ("35", "Botão 'Sim, cancelar inscrição'", "34", "Volta com a inscrição cancelada"),
    ("35", "Botão 'Manter'", "34", ""),
    ("36", "Botão 'Cancelar minha inscrição'", "35", ""),
    ("37", "Botão 'Validar'", "17", ""),
    ("37", "Botão 'Baixar PDF'", "21", "Abre o modelo do certificado"),
    ("38", "Botão 'Salvar alterações'", "29", ""),
    # ---------------- area do gestor
    ("39", "Menu lateral 'Cursos'", "40", ""),
    ("39", "Menu lateral 'Turmas'", "42", ""),
    ("39", "Menu lateral 'Inscrições'", "43", ""),
    ("39", "Menu lateral 'Fila de espera'", "45", ""),
    ("39", "Menu lateral 'Frequência'", "46", ""),
    ("39", "Menu lateral 'Certificados'", "47", ""),
    ("39", "Menu lateral 'Professores'", "48", ""),
    ("39", "Menu lateral 'Conteúdo do portal'", "49", ""),
    ("39", "Menu lateral 'Relatórios'", "52", ""),
    ("39", "Botão 'Novo curso'", "41", ""),
    ("39", "Pendência 'Lançar frequência'", "46", ""),
    ("39", "Pendência 'Emitir 30 certificados'", "47", ""),
    ("39", "Pendência 'Chamar 3 alunos da fila'", "45", ""),
    ("40", "Botão 'Novo curso' / ícone de editar", "41", ""),
    ("40", "Ícone de inscritos (bonequinhos)", "43", ""),
    ("40", "Ícone de visualizar (olho)", "05", "Mostra como o público vê"),
    ("41", "Botão 'Salvar e continuar'", "42", "Passo 2: turmas e vagas"),
    ("42", "Ícone de inscritos de uma turma", "43", ""),
    ("43", "Botão 'Cancelar' de uma inscrição", "44", "RF 11"),
    ("43", "Botão 'Chamar' de quem está na fila", "45", ""),
    ("44", "Botão 'Confirmar cancelamento' / 'Voltar'", "43", ""),
    ("45", "Botão 'Chamar agora'", "43", ""),
    ("46", "Botão 'Salvar frequência'", "47", "Libera a emissão"),
    ("47", "Botão 'Editar modelo do certificado'", "21", ""),
    ("49", "Aba 'Acervo / Biblioteca'", "50", ""),
    ("49", "Aba 'Escolas parceiras e páginas'", "51", ""),
    ("50", "Aba 'Notícias'", "49", ""),
    ("51", "Aba 'Notícias'", "49", ""),
    # ---------------- area do professor
    ("53", "Botão 'Ver alunos' de uma turma", "54", ""),
    ("53", "Botão 'Materiais' de uma turma", "55", ""),
    ("53", "Menu lateral 'Alunos inscritos'", "54", ""),
    ("53", "Menu lateral 'Materiais'", "55", ""),
    ("54", "Menu lateral 'Painel'", "53", ""),
    ("54", "Menu lateral 'Materiais'", "55", ""),
    ("55", "Menu lateral 'Painel'", "53", ""),
    ("55", "Menu lateral 'Alunos inscritos'", "54", ""),
]

# fluxo principal destacado no mapa
FLUXO = ["01", "02", "05", "22", "30", "32", "34", "37"]

# (numero, requisito, pergunta, opcao A, opcao B, telas)
DECISOES = [
    ("D1", "RF 2", "Para eventos online ou híbridos, de que forma o link deve ser disponibilizado?",
     "Opção 1 - Link exibido na própria página de detalhes do curso, visível a qualquer visitante.",
     "Opção 2 - Link liberado somente após o aluno realizar a inscrição no portal.",
     "05, 32, 36"),
    ("D2", "RF 2", "Como deve acontecer um curso online?",
     "Transmissão em plataforma externa (Meet, Teams, YouTube), com link publicado pelo portal.",
     "Ambiente próprio dentro do portal, com sala virtual e registro de acesso.",
     "05, 36"),
    ("D3", "RF 3", "Como as notícias em destaque chegam à página inicial?",
     "O gestor marca manualmente quais notícias ficam em destaque e em que ordem.",
     "O portal exibe automaticamente as N notícias mais recentes por data de cadastro.",
     "01, 49"),
    ("D4", "RF 4", "Qual formato de validação será impresso no PDF do certificado?",
     "Opção 1 - Apenas o código alfanumérico e o link do portal (digitação manual).",
     "Opção 2 - Código alfanumérico + QR Code, com validação instantânea pela câmera.",
     "20, 21, 47"),
    ("D5", "RF 4", "Quais dados aparecem na tela de sucesso da validação (LGPD)?",
     "Nome completo, CPF mascarado, curso, carga horária e data de conclusão.",
     "Acrescentar a matrícula nos casos de servidores da Casa.",
     "18"),
    ("D6", "RF 5", "Qual será o identificador principal de acesso (login)?",
     "Opção 1 (recomendada) - CPF. Garante unicidade e evita contas duplicadas.",
     "Opção 2 - E-mail. Padrão de mercado, mas o usuário pode trocar e perder o histórico.",
     "22, 23, 24, 26"),
    ("D7", "RF 5", "Como será o login dos servidores da Câmara Municipal do Recife?",
     "Integração com a rede interna via LDAP / Active Directory (Single Sign-On).",
     "Banco de senhas isolado no portal: o servidor cria e gerencia uma senha nova.",
     "22"),
    ("D8", "RF 5", "Haverá política de bloqueio contra ataque de força bruta?",
     "Sim - bloquear a conta por 30 minutos após 5 tentativas consecutivas malsucedidas.",
     "Definir outro número de tentativas e outro tempo de bloqueio.",
     "23"),
    ("D9", "RF 6", "Qual será o modelo de acesso do aluno?",
     "Opção 1 - Cadastro único com login e senha, com Área do Aluno, histórico e certificados.",
     "Opção 2 - Formulário aberto a cada curso, sem histórico e sem área do aluno.",
     "24, 29, 34, 37"),
    ("D10", "RF 6", "Confirmar os dados coletados no cadastro do aluno (finalidade LGPD).",
     "Nome, CPF, e-mail, telefone/WhatsApp, tipo de vínculo, matrícula (condicional) e senha.",
     "Retirar ou acrescentar campos após análise de finalidade específica.",
     "24, 38"),
    ("D11", "RF 7", "O mesmo aluno pode se inscrever em mais de uma turma do mesmo curso?",
     "Não - uma inscrição ativa por curso, liberando vaga para mais pessoas.",
     "Sim - permitido, por exemplo para reposição de conteúdo.",
     "30, 34"),
    ("D12", "RF 10", "Quando surgir vaga, como a fila de espera é chamada?",
     "Opção 1 - O sistema avisa o próximo por e-mail e dá 24h para assumir a vaga.",
     "Opção 2 - Manual: alguém da Escola entra em contato com o próximo da fila.",
     "33, 45"),
    ("D13", "RF 13", "Um curso pode ter várias turmas? Como divulgar dias e horários?",
     "Sim - cada turma com período, horário, local, professor e vagas próprios, exibidos na "
     "página do curso.",
     "Não - um curso equivale a uma única turma.",
     "07, 30, 42"),
    ("D14", "RF 14", "Qual a frequência mínima para emissão do certificado?",
     "75% da carga horária (proposta do protótipo).",
     "Outro percentual, com ou sem avaliação de aproveitamento.",
     "46, 47"),
]
